chore: bump RSDKUtils to 3.0.0, fix imports
rakutentech/ios-inappmessaging pull request #169
Opened 2022-04-10 22:00 UTC by imaginaris

# Description
* Updated RSDKUtils to 3.0.0
Main benefits: removed bundle assets workaround, precise error message when `toAfterTimeout()` fails in unit tests.
* Fixed imports in unit tests (unfortunately not all tests cases work properly in SPM mode)
* Added missing unit tests file 🤷 

# Checklist
- [X] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [X] I wrote/updated tests for new/changed code
- [X] I removed all sensitive data **before every commit**, including API endpoints and keys
- [] I ran `fastlane ci` without errors

2022-04-11 02:13 UTC, apparition47 requested changes

2022-04-11 02:13 UTC, apparition47 commented on Tests/Tests/ViewModelSpec.swift
> +                it("should return false if bodyMessage and header") {
and header..... ?

2022-04-11 02:13 UTC, apparition47 commented on Tests/Tests/ViewModelSpec.swift
> +                it("should return false if bodyMessage and header") {
and header..... ?

2022-04-11 07:16 UTC, imaginaris commented on Tests/Tests/ViewModelSpec.swift
> +                it("should return false if bodyMessage and header") {
oops. forgot to delete that part

2022-04-11 07:24 UTC, imaginaris commented on Sources/RInAppMessaging/Utilities/BundleInfo.swift
here I could just simply return `assetsBundle(bundleIdPhrase: "RInAppMessagingResources")`. The difference is that the current implementation tries to get resources based on IAM SDK bundle path where the other solution iterates over all available resource bundles. The current approach, to me, seems more precise and safe in terms of name conflicts etc (?). But I'm not sure if that's a good approach

2022-04-12 16:41 UTC, malayli approved these changes

2022-04-13 00:57 UTC, donnie-jp commented on fastlane/Fastfile
> +      ios_version = sh 'xcodebuild -showBuildSettings | grep "IPHONEOS_DEPLOYMENT_TARGET =" | tr -d "IPHONEOS_DEPLOYMENT_TARGET ="'
👍

2022-04-13 00:57 UTC, donnie-jp approved these changes

2022-04-13 03:11 UTC, apparition47 approved these changes

2022-04-22 05:02 UTC, merged