docs: update docs for 2.1.0 release
rakutentech/ios-inappmessaging pull request #17
Opened 2020-11-10 08:56 UTC by imaginaris

# Description
Version bump to 2.1.0
Changelog updates.

## Links
PRM-1249
SDKCF-2681

# Checklist
- [X] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [X] I removed all sensitive data **before every commit**, including API endpoints and keys
- [ ] I ran `fastlane ci` without errors

2020-11-10 09:22 UTC, malayli approved these changes

2020-11-10 09:45 UTC, donnie-jp commented on CHANGELOG.md
> +### 2.1.0 (2020-11-11)
I think it's useful to add a SDKCF-1234 text (not link) at the end if there is a relevant JIRA

2020-11-10 09:47 UTC, donnie-jp requested changes
Please also update the version in the` .jazzy.yml` file so that our generated docs show the correct version

2020-11-10 10:36 UTC, imaginaris commented
> Please also update the version in the` .jazzy.yml` file so that our generated docs show the correct version

Ah those hidden files. Nice catch!

2020-11-11 01:37 UTC, donnie-jp approved these changes

2020-11-11 01:37 UTC, merged