tests: improve Code Coverage of ConfigurationService (SDKCF-6388)
rakutentech/ios-inappmessaging pull request #261
Opened 2023-03-30 05:47 UTC by ts-robih-robihamanto

# Description
Improved coverage of `ConfigurationService` to **96.8%**
It wasn't possible to cover assertionFailure lines, it's making the app crash and won't continue:
```swift
if !headerBuilder.addSubscriptionID(configurationRepository: configurationRepository) {
    Logger.debug("Info.plist must contain a valid InAppMessagingAppSubscriptionID")
    assertionFailure()
}
```
This else line cannot failed, because it's already checked in the previous line if it's link is a valid URL:
```swift
guard let url = urlComponents?.url else {
    return .failure(RequestError.urlIsNil)
}
```

## Links
SDKCF-6388

# Checklist
- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have added to the [changelog](../blob/master/CHANGELOG.md#Unreleased)
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data **before every commit**, including API endpoints and keys, and internal links
- [ ] I ran `fastlane ci` without errors
- [x] All project file changes are replicated in `SampleSPM/SampleSPM.xcodeproj` project

2023-03-30 09:03 UTC, imaginaris requested changes
The `assertionFailure()` in `buildRequestHeader()` can be tested by setting subscription id to nil and using `to(throwAssertion())` predicate. It won't crash the unit test run

2023-03-30 09:03 UTC, imaginaris commented on Tests/Tests/ConfigurationServiceSpec.swift
> +                it("will return RequestError.bodyIsNil") {
please add test cases that check if the same is returned when you pass a non-nil parameter in `buildHttpBody()` so it's clear that `bodyIsNil` is always returned no matter what parameter is passed

2023-03-31 07:18 UTC, ts-robih-robihamanto commented
> The `assertionFailure()` in `buildRequestHeader()` can be tested by setting subscription id to nil and using `to(throwAssertion())` predicate. It won't crash the unit test run

I added the case for throwAssertion here [0726cfa](https://github.com/rakutentech/ios-inappmessaging/pull/261/commits/62da5bc73d4b56f83df4c5bd4f4234dd20726cfa).

2023-04-02 22:25 UTC, imaginaris approved these changes
👍

2023-04-03 03:45 UTC, merged