docs: update openapi documentation based on current code (SDKCF-6592)
rakutentech/ios-inappmessaging pull request #286
Opened 2023-06-01 07:03 UTC by ts-robih-robihamanto

# Description
Update `openapi.yml` file in the repo with the recent changes in the backend API.

## Links
SDKCF-6592

# Checklist
- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have added to the [changelog](../blob/master/CHANGELOG.md#Unreleased)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data **before every commit**, including API endpoints and keys, and internal links
- [ ] I ran `fastlane ci` without errors
- [ ] All project file changes are replicated in `SampleSPM/SampleSPM.xcodeproj` project

2023-06-01 07:30 UTC, ts-dzmitry-kurski approved these changes

2023-06-04 22:31 UTC, imaginaris requested changes

2023-06-04 22:31 UTC, imaginaris commented on openapi.yaml
> +      - name: easy_id
Please remove all `easy_id` references as the SDK doesn't send them

2023-06-04 22:31 UTC, imaginaris commented on openapi.yaml
> +          description: Actions -> 0 - INVALID, 1 - Redirect, 2 - Deeplink, 3 - Close, 4 - Push Premier
typo: "Premier" -> "Primer"

2023-06-04 22:31 UTC, imaginaris commented on openapi.yaml
> +                  maxImpressions:
I can't believe this basic property was missing here 😅

2023-06-04 22:31 UTC, imaginaris commented on openapi.yaml
> +                            type: boolean
please add `description: If true, the messageBody value is treated as HTML content`

2023-06-05 22:00 UTC, imaginaris commented on openapi.yaml
> +      - name: easy_id
please remove this entry as well

2023-06-05 22:00 UTC, imaginaris commented on openapi.yaml
> +      - name: easy_id
please remove this entry as well

2023-06-06 21:58 UTC, imaginaris approved these changes

2023-06-07 07:06 UTC, merged