SDKCF-3976 campaign display iff display permission request succeeds
rakutentech/ios-inappmessaging pull request #94
Opened 2021-07-08 12:45 UTC by apparition47

# Description

Align with Android behaviour to only display campaigns if Display permission request succeeds

## Links

SDKCF-3976

# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data **before every commit**, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

2021-07-08 20:51 UTC, imaginaris requested changes
Overall everything ok, just one test case to be updated.
Also please fix the typo in the commit message :)

2021-07-08 20:51 UTC, imaginaris commented on Tests/DisplayPermissionServiceSpec.swift
> +                        expect(result.display).to(beFalse())
I guess the test name has to be updated as well

2021-07-12 07:29 UTC, imaginaris approved these changes
👍 Don't forget about the typo 😉

2021-07-13 01:37 UTC, apparition47 commented
Typo? Are you referring to my ["iff" -- if and only if](https://en.wikipedia.org/wiki/If_and_only_if)?

2021-07-13 07:31 UTC, imaginaris commented
> Typo? Are you referring to my ["iff" -- if and only if](https://en.wikipedia.org/wiki/If_and_only_if)?

Oh... I didn't know that abbreviation 😞 Sorry.

2021-07-13 09:47 UTC, merged